title: Yamendra Gurung
logo: /assets/img/profile_pic.jpg
description: |
  Sustainable Energy | Climate Change| MBA | Electrical Engineer <br>
  ğŸ“ Address: Waling-01, Syangja, Gandaki Province, Nepal  <br>
  ğŸ’¼ Work: Department Head, Electrical division at Smart Solar Nepal Corporation  <br>
  âœ‰ï¸ Email: yamendra.grg23@gmail.com  <br>
  ğŸ“ Phone: +977-9851243331 <br>
  ğŸ”— LinkedIn: <a href="https://www.linkedin.com/in/yamendra23/" target="_blank">link</a>  <br>
  ğŸŒ Nationality: Nepalese <br>
# show_downloads: true
theme: jekyll-theme-minimal
