title: Yamendra Gurung
logo: /assets/img/profile_pic.jpg
description: |
  NEC Category A Registered, Electrical Engineer
  ğŸ“ Address: Waling-01, Syangja, Gandaki Province, Nepal  
  ğŸ’¼ Work: Department Head, Electrical division at Smart Solar Nepal Corporation  
  âœ‰ï¸ Email: yamendra.grg23@gmail.com  
  ğŸ“ Phone: +977-9851243331
  ğŸ”— LinkedIn: [https://www.linkedin.com/in/yamendra23/](https://www.linkedin.com/in/yamendra23/)  
  ğŸŒ Nationality: Nepalese
# show_downloads: true
theme: jekyll-theme-minimal
